### ISSUE TITLE
Plenary speakers

### ISSUE THREAD

**Issue by miguel-mx** [miguel-mx/PRIMA#2]
Universidades

**Comment by ghost** [comment]
Maryam Mirzakhani
[Teichmuller theory, hyperbolic geometry]
Stanford

Fernando Coda Marques
[Geometric analysis]
Princeton

Hiraku Nakajima
[Repr theory/math phys]
RIMS Kyoto Japan

Geoff Whittle
[Matroid theory]
Victoria University, New Zealand

Kerry Landman
[Models for appl. biology & tissue eng]
University of Melbourne, Australia

Ana Amador
[Applied dynamical systems/bird songs]
Universidad de Buenos Aires, Argentina

William Duke
[Number theory]
UCLA

Hee Oh
[Dynamical systems]
Yale

Manuel del Pino
[PDE]
U. de Chile

David Brydges
[Probability and math physics]
UBC, Canada

Chenyang Xu
[Algebraic geometry]
Peking Univ.

Ian Agol
[Topology]
Berkeley

Lexing Ying
[Scientific computing]
Stanford

Alexey Bondal
[Geometry & physics]
Kavli IPMU (Tokyo) & Steklov Institute
